services:
  - type: web
    name: multiple-llm-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host=0.0.0.0 --port=10000

  - type: web
    name: multiple-llm-frontend
    env: python
    rootDir: frontend
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10001 --server.address=0.0.0.0
