services:
  - type: web
    name: llm-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/server.py
    plan: starter  # or standard if needed
